### PR TITLE
I am getting an error that I think may not be intended.

### PR DESCRIPTION
**Pull request by clburns107**
I was able to fix the first error and close the parenthasis to run rackup
After running rackup this is the error I receive

2016-02-08 12:28:38 - ActiveRecord::NoDatabaseError - FATAL:  database "postgres://localhost/debugging-challenge" does not exist

### CODE REVIEW

**Comment by sumeetjain** [comment]
Seems like quite a few folks are getting this error. My bad! Working on it.

**Comment by sumeetjain** [comment]
Solved? Or still a problem?

**Comment by clburns107** [comment]
I stared at this for a couple hours last night trying to find an error.  The page loads the standard 404 error and my server gives this> [2016-02-09 08:44:20] INFO  WEBrick 1.3.1
[2016-02-09 08:44:20] INFO  ruby 2.3.0 (2015-12-25) [x86_64-darwin15]
[2016-02-09 08:44:20] INFO  WEBrick::HTTPServer#start: pid=15753 port=9292
::1 - - [09/Feb/2016:08:44:24 -0600] "GET /assignment/1 HTTP/1.1" 404 514 0.0440
::1 - - [09/Feb/2016:08:44:24 -0600] "GET /**sinatra**/404.png HTTP/1.1" 304 - 0.0015

From this information I have no IDEA what step to take next. None of this looks like a ruby error clue to me.

**Comment by clburns107** [comment]
im stuck again.  I think  this is saying the method is missing from the attribute_methods.rb file but I dont see that file to look for the method.  Or know what method to replace it with...

NoMethodError at /assignment/1
undefined method `adjusted_grade' for #<Student id: 1, name: "Diana Mkrtchyan">
file: attribute_methods.rb location: method_missing line: 433

**Comment by sumeetjain** [comment]
That is an intended error.

The line of code it's complaining about has `s.adjusted_grade(@assignment)` on it. It's saying `adjusted_grade` is not a method for `s`.

So first, what is `s`? A String? An Array? Maybe a custom object?

Once you figure that out, go to that class's documentation. (Or if it's a custom object, go to the file where that class's methods are all defined.) Then look through that to see if either 1) the `adjusted_grade` does exist, but it's misspelled, or 2) the `adjusted_grade` method doesn't exist, but something like it does (in which case you should update the view to call that method instead).

**Pull request closed without merging**
